### ISSUE TITLE
[BUG] Unfortunately not yet compatible with 1.21.1

### ISSUE THREAD

**Issue by savdbroek** [cobrex1/TownyMenu#20]
**Describe the bug**
Plugin is currently incompatible with 1.21.1. It loads up fine, but trying to click any button in the GUI results in the following error:

**To Reproduce**
1. Install TownyMenu on a 1.21.1 server
2. Try to run /plm
3. Click any button
4. Observe the error

**Expected behavior**
The button to work:)

**Plugin Version:**
1.8.7

**Server Jar and Version:**
Purpur 2287

**Additional context**
Error:
`[16:58:23 ERROR]: TownyMenu 1.8.7 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file. Running Purpur 1.21.1-R0.1-SNAPSHOT and Java 21.0.4
[16:58:23 INFO]: java.lang.NoClassDefFoundError: Could not initialize class me.cobrex.TownyMenu.lib.fo.remain.nbt.NBTReflectionUtil
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.remain.nbt.NBTCompound.hasTag(NBTCompound.java:699)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.matchNbt(ItemUtil.java:208)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.isSimilar(ItemUtil.java:175)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.menu.Menu.getButton(Menu.java:388)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.menu.MenuListener.onMenuClick(MenuListener.java:97)
[16:58:23 INFO]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor714.execute(Unknown Source)
[16:58:23 INFO]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[16:58:23 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:58:23 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:58:23 INFO]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[16:58:23 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[16:58:23 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[16:58:23 INFO]: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
[16:58:23 INFO]:        at java.base/java.util.ImmutableCollections$MapN.probe(Unknown Source)
[16:58:23 INFO]:        at java.base/java.util.ImmutableCollections$MapN.get(Unknown Source)
[16:58:23 INFO]:        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(Unknown Source)
[16:58:23 INFO]:        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79)
[16:58:23 INFO]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90)
[16:58:23 INFO]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.remain.nbt.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:50)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.remain.nbt.NBTCompound.hasTag(NBTCompound.java:699)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.matchNbt(ItemUtil.java:208)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.isSimilar(ItemUtil.java:175)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.menu.Menu.getButton(Menu.java:388)
[16:58:23 INFO]:        at TownyMenu-1.8.7.jar//me.cobrex.TownyMenu.lib.fo.menu.MenuListener.onMenuClick(MenuListener.java:97)
[16:58:23 INFO]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor714.execute(Unknown Source)
[16:58:23 INFO]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[16:58:23 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:58:23 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:58:23 INFO]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[16:58:23 INFO]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[16:58:23 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[16:58:23 INFO]: [TownyMenu] !-----------------------------------------------------!
[16:58:23 INFO]: [TownyMenu]  Error clicking in menu PlotMenu{}
[16:58:23 INFO]: [TownyMenu] !-----------------------------------------------------!`

**Comment by cobrex1** [comment]
Sorry for the delay, please also try 1.8.9 - this should fix the issues.
