### ISSUE TITLE
1.21.3 not support yet?

### ISSUE THREAD

**Issue by F-luxus** [cobrex1/TownyMenu#25]
I have tried this plugin on fresh Purpur 1.21.3-R0.1-SNAPSHOT ,Towny v0.100.4.13 and Java 21.0.5.
When clicking somwhere in GUI getting error. 
Log file:
More Information: 

> Error clicking in menu JoinTownMenu{}
> ExceptionInInitializerError (Unknown cause)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.remain.nbt.NBTCompound.hasTag(NBTCompound.java:699)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.matchNbt(ItemUtil.java:208)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.isSimilar(ItemUtil.java:175)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.menu.Menu.getButton(Menu.java:395)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.menu.MenuListener.onMenuClick(MenuListener.java:98)
> 	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor202.execute(Unknown Source)
> 	 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
> 	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
> 	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> 	 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
> 	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
> 	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
> NullPointerException Cannot invoke "Object.hashCode()" because "pk" is null
> 	 at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328)
> 	 at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242)
> 	 at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097)
> 	 at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79)
> 	 at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90)
> 	 at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.remain.nbt.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:50)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.remain.nbt.NBTCompound.hasTag(NBTCompound.java:699)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.matchNbt(ItemUtil.java:208)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.ItemUtil.isSimilar(ItemUtil.java:175)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.menu.Menu.getButton(Menu.java:395)
> 	 at TownyMenu-1.8.9.jar//me.cobrex.TownyMenu.lib.fo.menu.MenuListener.onMenuClick(MenuListener.java:98)
> 	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor202.execute(Unknown Source)
> 	 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
> 	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
> 	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> 	 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
> 	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
> 	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)

**Comment by cobrex1** [comment]
Please try 1.8.10
This should be resolved, and thanks for reporting
